baseurl = "https://www.graphql-java-kickstart.com/"
languageCode = "en-us"
title = "GraphQL Java Kickstart"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "GraphQL Java Kickstart"
	description = "Documentation for GraphQL Java Servlet"
	copyright = "Released under the Apache 2.0 license"

	# Repository
	provider = "GitHub"
	repo_name = "graphql-java-kickstart"
	repo_url = "https://github.com/graphql-java-kickstart"

	version = "6.3.0"
	favicon = "images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.feature]
		search = true
		tabs = true

	[[params.repositories]]
		name = "graphql-java-kickstart/graphql-java-servlet"
		url = "https://github.com/graphql-java-kickstart/graphql-java-servlet"
		menu = "Servlet"

	[[params.repositories]]
		name = "graphql-java-kickstart/graphql-java-tools"
		url = "https://github.com/graphql-java-kickstart/graphql-java-tools"
		menu = "Tools"

	[[params.repositories]]
		name = "graphql-java-kickstart/graphql-spring-boot"
		url = "https://github.com/graphql-java-kickstart/graphql-spring-boot"
		menu = "Spring Boot"

  [[params.repositories]]
    name = "graphql-java-kickstart/graphql-spring-webclient"
    url = "https://github.com/graphql-java-kickstart/graphql-spring-webclient"
    menu = "Web Client"

  [[params.repositories]]
    name = "graphql-java-kickstart/samples"
    url = "https://github.com/graphql-java-kickstart/samples"
    menu = "Samples"

  [[params.repositories]]
    name = "philip-jvm/learn-spring-boot-graphql"
    url = "https://github.com/philip-jvm/learn-spring-boot-graphql"
    menu = "Tutorials"

	[params.logo]
		icon = ""
		image = "images/logo-graphql-kickstart-2000px.png"

	[params.palette]
    	primary = "pink"
    	accent  = "teal"

  [params.font]
  	text = "Roboto"
  	code = "Roboto Mono"


[social]
	twitter = ""
	github  = "https://github.com/graphql-java-kickstart"
	email   = ""


[[menu.main]]
	name   = "Tools"
	url    = "/tools/"
	weight = 10

[[menu.main]]
	name   = "Servlet"
	url    = "/servlet/"
	weight = 20

[[menu.main]]
	name   = "Spring Boot"
	url    = "/spring-boot/"
	weight = 30

[[menu.main]]
	name   = "Web Client"
	url    = "/web-client/"
	weight = 40

[[menu.main]]
	name   = "Samples"
	url    = "/samples/"
	weight = 50

[[menu.main]]
	name   = "Tutorials"
	url    = "/tutorials/"
	weight = 60

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[outputs]
home = ["HTML", "RSS", "JSON"]
